debug: true
slacktoken: "3472a99d2479142d5c2bbca5bce176ce35a61410"
telegramtoken: "40ce31d80a89a3d3c4d3f73194f7208ba3359c5c"
irc:
    server: "irc.freenode.net:6697"
    channels:
        - "#channel"
        - "#another"
    user: "robot"
    nick: "bot"
    password: "123secret"
    usetls: false
    tlsservername: ""
    debug: true
